services:
  threads-api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: threads-api
    environment:
      DB_PORT: $DB_PORT
      SERVER_PORT: $SERVER_PORT
      HOST: $HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  postgresql:
    image: postgres
    container_name: threads-db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./api/postgres/data:/var/lib/postgresql/data
